add more ts mode from tree-sitter-module
renzmann/treesit-auto pull request #42
Opened 2023-04-06 20:23 UTC by getong

This is a copy from https://github.com/casouri/tree-sitter-module
just copy the url from build.sh

2023-10-19 02:45 UTC, renzmann commented
Thanks for contributing all these!  I'm going to wait on #43, #53, and #54 before diving into these too deep, since it looks like there's some overlap between the modes they would be remapping alongside these.

2023-11-11 04:03 UTC, renzmann requested changes
One quick thing before we bring these in: mind adding the `:ext ...` keyword to each of these recipes?  (documented [here](https://github.com/renzmann/treesit-auto/blob/main/CONTRIBUTING.org))  This would enable a few features of `treesit-auto` that could enable and/or install these modes based on the file extension.

2023-11-11 04:03 UTC, renzmann commented on treesit-auto.el
> -      :lang 'proto
Issue: It looks like we have an accidental overwrite of the `:lang 'proto` that's required here.

2023-11-12 16:46 UTC, getong commented
surface file is elixir filename extension, ignore it. The other new added lang have added the ext name.

2024-04-01 14:49 UTC, closed without merging